-- 1. Events Table
CREATE TABLE IF NOT EXISTS events (
    event_id TEXT PRIMARY KEY,
    category TEXT NOT NULL,
    price DECIMAL NOT NULL DEFAULT 0,
    capacity INTEGER NOT NULL DEFAULT 100,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Combos Table
CREATE TABLE IF NOT EXISTS combos (
    combo_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    price DECIMAL NOT NULL DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Combo Rules Table
CREATE TABLE IF NOT EXISTS combo_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    combo_id TEXT REFERENCES combos(combo_id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    allowed_count INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Registrations Table
CREATE TABLE IF NOT EXISTS registrations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    event_id TEXT REFERENCES events(event_id),
    combo_id TEXT REFERENCES combos(combo_id),
    payment_status TEXT DEFAULT 'pending',
    payment_id TEXT,
    qr_code_string TEXT UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Profiles Table
CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT NOT NULL,
    gender TEXT,
    college_name TEXT,
    department TEXT,
    year_of_study TEXT,
    roll_number TEXT,
    mobile_number TEXT,
    role TEXT DEFAULT 'student',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 6. Teams Table
CREATE TABLE IF NOT EXISTS teams (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    event_id TEXT REFERENCES events(event_id),
    created_by UUID REFERENCES profiles(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 7. Team Members Table
CREATE TABLE IF NOT EXISTS team_members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id UUID REFERENCES teams(id) ON DELETE CASCADE,
    user_id UUID REFERENCES profiles(id),
    role TEXT DEFAULT 'member', -- 'lead' or 'member'
    status TEXT DEFAULT 'joined', -- 'invited' or 'joined'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(team_id, user_id)
);

-- 8. Capacity Check Trigger
CREATE OR REPLACE FUNCTION check_capacity()
RETURNS TRIGGER AS $$
DECLARE
    current_count INTEGER;
    max_capacity INTEGER;
BEGIN
    -- Get current registration count for the event
    SELECT COUNT(*) INTO current_count FROM registrations WHERE event_id = NEW.event_id;
    
    -- Get capacity for the event
    SELECT capacity INTO max_capacity FROM events WHERE event_id = NEW.event_id;
    
    IF current_count >= max_capacity THEN
        RAISE EXCEPTION 'Event capacity reached';
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_check_capacity ON registrations;
CREATE TRIGGER trg_check_capacity
BEFORE INSERT ON registrations
FOR EACH ROW
EXECUTE FUNCTION check_capacity();

-- RLS POLICIES

-- Enable RLS
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE combos ENABLE ROW LEVEL SECURITY;
ALTER TABLE combo_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid "already exists" errors
DROP POLICY IF EXISTS "Allow public read access to active events" ON events;
DROP POLICY IF EXISTS "Allow public read access to active combos" ON combos;
DROP POLICY IF EXISTS "Allow public read access to combo rules" ON combo_rules;
DROP POLICY IF EXISTS "Users can view their own registrations" ON registrations;
DROP POLICY IF EXISTS "Users can insert their own registrations" ON registrations;
DROP POLICY IF EXISTS "Users can view their own profile" ON profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON profiles;
DROP POLICY IF EXISTS "Users can view teams they are members of" ON teams;
DROP POLICY IF EXISTS "Users can view team members of their teams" ON team_members;
DROP POLICY IF EXISTS "Admins can do everything on events" ON events;
DROP POLICY IF EXISTS "Admins can do everything on combos" ON combos;
DROP POLICY IF EXISTS "Admins can do everything on combo_rules" ON combo_rules;
DROP POLICY IF EXISTS "Admins can view all registrations" ON registrations;
DROP POLICY IF EXISTS "Admins can view all profiles" ON profiles;

-- Events: Everyone can read active events
CREATE POLICY "Allow public read access to active events" ON events
    FOR SELECT USING (is_active = true);

-- Profiles: Users can manage their own profile
CREATE POLICY "Users can view their own profile" ON profiles
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile" ON profiles
    FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile" ON profiles
    FOR INSERT WITH CHECK (auth.uid() = id);

-- Combos: Everyone can read active combos
CREATE POLICY "Allow public read access to active combos" ON combos
    FOR SELECT USING (is_active = true);

-- Combo Rules: Everyone can read combo rules
CREATE POLICY "Allow public read access to combo rules" ON combo_rules
    FOR SELECT USING (true);

-- Registrations: Users can read their own registrations
CREATE POLICY "Users can view their own registrations" ON registrations
    FOR SELECT USING (auth.uid() = user_id);

-- Registrations: Users can insert their own registrations
CREATE POLICY "Users can insert their own registrations" ON registrations
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Admin Policies (Assuming a 'role' claim in auth.users or a separate profiles table)
-- For simplicity, we can use a check for a specific email or a custom claim if set up.
-- Here we just provide the structure for admin access.
CREATE POLICY "Super Admins can do everything on events" ON events
    FOR ALL USING (get_user_role() = 'super_admin');

CREATE POLICY "Super Admins can do everything on combos" ON combos
    FOR ALL USING (get_user_role() = 'super_admin');

CREATE POLICY "Super Admins can do everything on combo_rules" ON combo_rules
    FOR ALL USING (get_user_role() = 'super_admin');

CREATE POLICY "Staff can view all registrations" ON registrations
    FOR SELECT USING (
        get_user_role() IN ('super_admin', 'registration_admin') OR 
        is_event_coordinator(event_id)
    );

-- Teams: Users can view teams they are members of
CREATE POLICY "Users can view teams they are members of" ON teams
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM team_members 
            WHERE team_members.team_id = teams.id 
            AND team_members.user_id = auth.uid()
        )
    );

-- Team Members: Users can view team members of their teams
-- Using a security definer function to avoid infinite recursion in RLS
CREATE OR REPLACE FUNCTION check_team_membership(t_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM team_members
        WHERE team_id = t_id
        AND user_id = auth.uid()
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE POLICY "Users can view team members of their teams" ON team_members
    FOR SELECT USING (
        check_team_membership(team_id)
    );

-- 9. Attendance Table
CREATE TABLE IF NOT EXISTS attendance (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    event_id TEXT REFERENCES events(event_id),
    marked_by UUID REFERENCES profiles(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(user_id, event_id)
);

-- 10. Winners Table
CREATE TABLE IF NOT EXISTS winners (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    event_id TEXT REFERENCES events(event_id),
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    position INTEGER NOT NULL, -- 1, 2, 3
    certificate_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(event_id, position)
);

-- 11. Event Coordinators Table
CREATE TABLE IF NOT EXISTS event_coordinators (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    event_id TEXT REFERENCES events(event_id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(user_id, event_id)
);

-- Enable RLS on new tables
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE winners ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_coordinators ENABLE ROW LEVEL SECURITY;

-- Helper function to get user role
CREATE OR REPLACE FUNCTION get_user_role()
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT role FROM profiles WHERE id = auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Helper function to check if user is coordinator for an event
CREATE OR REPLACE FUNCTION is_event_coordinator(e_id TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM event_coordinators
    WHERE user_id = auth.uid() AND event_id = e_id
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Updated Admin/Coordinator Policies

-- Profiles: Admins can view all profiles
CREATE POLICY "Admins can view all profiles" ON profiles
    FOR SELECT USING (get_user_role() IN ('super_admin', 'registration_admin'));

-- Registrations: Admins and Coordinators can view registrations
-- (Already covered by "Staff can view all registrations" above, but keeping for clarity if needed)
-- DROP POLICY IF EXISTS "Admins and Coordinators can view registrations" ON registrations;

-- Registrations: Reg Admins can update payment status
CREATE POLICY "Reg Admins can update payment status" ON registrations
    FOR UPDATE USING (get_user_role() IN ('super_admin', 'registration_admin'));

-- Attendance: Coordinators and Volunteers can mark attendance
CREATE POLICY "Coordinators and Volunteers can view attendance" ON attendance
    FOR SELECT USING (
        get_user_role() IN ('super_admin', 'volunteer') OR 
        is_event_coordinator(event_id)
    );

CREATE POLICY "Coordinators and Volunteers can insert attendance" ON attendance
    FOR INSERT WITH CHECK (
        get_user_role() IN ('super_admin', 'volunteer') OR 
        is_event_coordinator(event_id)
    );

-- Winners: Coordinators can manage winners
CREATE POLICY "Coordinators can manage winners" ON winners
    FOR ALL USING (
        get_user_role() = 'super_admin' OR 
        is_event_coordinator(event_id)
    );
